# Import Lib & Data Set

In [1]:
import pandas as pd
import numpy as np
df_mat=pd.read_excel("Material Planning.xlsx","Material Info")
df_pro=pd.read_excel("Material Planning.xlsx","Production Info")

In [2]:
df_mat.head(3)

,Material Name,Brand,UOM,Stock on Hand,Usage per gram,Safety Stock DOC,Medium Stock DOC,Maximum Stock DOC,Average daily Usage
0,Animal Fat,Luxe Bar,KG,2000000.0,45.0,29.874138,66.117334,95.185000,45699.652917
1,Plant Oil,Luxe Bar,KG,900000.0,41.0,29.874138,66.117334,95.185000,41637.461546
2,Caustic Soda,Luxe Bar,KG,6500000.0,43.0,19.004053,51.945597,70.685992,270989.335287

In [3]:
df_pro.head(3)

,Date,Luxe Bar 20g,Luxe Liquid 250ml,Luxe Liquid 500ml,Luxe Liquid 1000ml,Luxe Powder 15g,Luxe Powder 30g,Luxe Powder 90g,Luxe Powder 200g,Luxe Powder 400g,Luxe Powder 500g,Luxe Powder 900g
0,2024-01-01,20000.0,97561.0,49882.0,13429.0,22902.0,46285.0,33781.0,51620.0,36219.0,70082.0,41781.0
1,2024-02-01,24830.0,73752.0,49392.0,18745.0,28161.0,41677.0,39233.0,67862.0,34176.0,88703.0,40359.0
2,2024-03-01,20467.0,85310.0,49304.0,14203.0,25724.0,40234.0,35662.0,66818.0,30349.0,75734.0,46737.0

# Marterial Planning for Luxe Bar 20g

In [4]:
df_20g_pro=df_pro[["Date","Luxe Bar 20g"]]
df_20g_pro=df_20g_pro.rename(columns={"Luxe Bar 20g" : "Quantity"})
df_20g_pro.head()

        Date  Quantity
0 2024-01-01   20000.0
1 2024-02-01   24830.0
2 2024-03-01   20467.0
3 2024-04-01   34000.0
4 2024-05-01   29397.0

In [5]:
# filter out materials for Luxe Bar production
df_20g_mat=df_mat[df_mat["Brand"]== "Luxe Bar"]
df_20g_mat

,Material Name,Brand,UOM,Stock on Hand,Usage per gram,Safety Stock DOC,Medium Stock DOC,Maximum Stock DOC,Average daily Usage
0,Animal Fat,Luxe Bar,KG,2.000000e+06,45.0,29.874138,66.117334,95.185000,45699.652917
1,Plant Oil,Luxe Bar,KG,9.000000e+05,41.0,29.874138,66.117334,95.185000,41637.461546
2,Caustic Soda,Luxe Bar,KG,6.500000e+06,43.0,19.004053,51.945597,70.685992,270989.335287
3,Alkali,Luxe Bar,KG,1.200000e+06,33.0,29.874138,66.117334,95.185000,33513.078806
4,Sodium Hydroxide,Luxe Bar,KG,1.897815e+06,20.0,29.874138,66.117334,95.185000,20310.956852
5,Potassium hydroxide,Luxe Bar,KG,8.000000e+06,41.0,27.819085,85.535241,112.936134,258385.180157
6,colorant,Luxe Bar,KG,8.000000e+05,36.0,29.874138,66.117334,95.185000,36559.722333
7,Texture,Luxe Bar,KG,1.000000e+06,20.0,29.874138,66.117334,95.185000,20310.956852
8,Scent,Luxe Bar,KG,1.780654e+06,50.0,29.874138,66.117334,95.185000,50777.392130
9,Silica,Luxe Bar,KG,1.521684e+06,37.0,29.874138,66.117334,95.185000,37575.270176
10,marble pumice,Luxe Bar,KG,1.000779e+06,29.0,22.582726,48.700712,70.680807,29450.887435
11,Talc,Luxe Bar,KG,1.438845e+06,34.0,29.874138,66.117334,95.185000,34528.626648
25,Shrink Wrap,Luxe Bar,KG,9.254280e+05,48.0,29.874138,66.117334,95.185000,48746.296444
26,Luxe Bar Box,Luxe Bar,Pcs,1.252262e+06,20.0,29.874138,66.117334,95.185000,20310.956852
27,Luxe Bar Label,Luxe Bar,Pcs,1.504523e+06,40.0,29.874138,66.117334,95.185000,40621.913704
30,Luxe Bar Carton,Luxe Bar,Pcs,2.761308e+04,1.0,29.874138,66.117334,95.185000,1015.547843

In [6]:
pd.options.display.float_format = '{:.2f}'.format
import warnings
warnings.filterwarnings("ignore")

In [7]:
# week 1 planning
Wk1=df_20g_mat[["Material Name","Stock on Hand","UOM","Safety Stock DOC","Medium Stock DOC","Maximum Stock DOC"]]

# Calc usage
Wk1["Usage"]=df_20g_mat["Usage per gram"] * df_20g_pro["Quantity"]

# Calc DOC-Days of Cover= stock on hand/(average monthly usage/period)
Wk1["DOC"]=Wk1["Stock on Hand"]/df_20g_mat["Average daily Usage"]

# Calc reorder level 
dif= df_20g_mat["Maximum Stock DOC"]-Wk1["DOC"]
Wk1["Reorder Qty"]= dif * df_20g_mat["Average daily Usage"]

# Calc closing stock
Wk1["Closing Stock"]= Wk1["Stock on Hand"] - Wk1["Usage"] + Wk1["Reorder Qty"]

Wk1.head(3)

,Material Name,Stock on Hand,UOM,Safety Stock DOC,Medium Stock DOC,Maximum Stock DOC,Usage,DOC,Reorder Qty,Closing Stock
0,Animal Fat,2000000.00,KG,29.87,66.12,95.19,900000.00,43.76,2349921.46,3449921.46
1,Plant Oil,900000.00,KG,29.87,66.12,95.19,1018030.00,21.62,3063261.78,2945231.78
2,Caustic Soda,6500000.00,KG,19.00,51.95,70.69,880081.00,23.99,12655150.08,18275069.08

# 3 year plan

In [8]:
def mrp (df_mat,df_pro,pro_date,soh):
    
    plan=df_20g_mat[["Material Name","Stock on Hand","UOM","Safety Stock DOC","Medium Stock DOC","Maximum Stock DOC"]]
    
    # Calc prod qty
    plan["qty"]=df_20g_pro[df_20g_pro["Date"]==pro_date]["Quantity"].values[0]
   
    # Calc soh
    plan["Stock on Hand"]= soh
    
    # Calc usage
    plan["Usage"]=df_20g_mat["Usage per gram"] * plan["qty"]

    # Calc DOC-Days of Cover= stock on hand/(average monthly usage/period)
    plan["DOC"]=soh/df_20g_mat["Average daily Usage"]

    # Calc reorder level 
    dif= df_20g_mat["Maximum Stock DOC"]-plan["DOC"]
    plan["Reorder Qty"]= dif * df_20g_mat["Average daily Usage"]

    # Calc closing stock
    plan["Closing Stock"]=plan["Stock on Hand"] - plan["Usage"] + plan["Reorder Qty"]
    
    # Add production date:
    plan["Date"]= pro_date
    
    # Return the new DataFrame with calculated values and date
    return plan[["Date","Material Name","Stock on Hand","UOM","Safety Stock DOC","Usage","DOC","Reorder Qty", "Closing Stock"]]

In [9]:
mth_1 = mrp (df_20g_pro, df_20g_mat,pro_date="2024-01-01", soh= df_20g_mat["Stock on Hand"])
mth_1.head(3)

,Date,Material Name,Stock on Hand,UOM,Safety Stock DOC,Usage,DOC,Reorder Qty,Closing Stock
0,2024-01-01,Animal Fat,2000000.00,KG,29.87,900000.00,43.76,2349921.46,3449921.46
1,2024-01-01,Plant Oil,900000.00,KG,29.87,820000.00,21.62,3063261.78,3143261.78
2,2024-01-01,Caustic Soda,6500000.00,KG,19.00,860000.00,23.99,12655150.08,18295150.08

In [10]:
mth_2 = mrp (df_20g_pro, df_20g_mat,"2024-02-01", soh= mth_1["Closing Stock"])
mth_2.head(3)

,Date,Material Name,Stock on Hand,UOM,Safety Stock DOC,Usage,DOC,Reorder Qty,Closing Stock
0,2024-02-01,Animal Fat,3449921.46,KG,29.87,1117350.00,75.49,900000.00,3232571.46
1,2024-02-01,Plant Oil,3143261.78,KG,29.87,1018030.00,75.49,820000.00,2945231.78
2,2024-02-01,Caustic Soda,18295150.08,KG,19.00,1067690.00,67.51,860000.00,18087460.08

## Automate for all months

In [11]:
df_3yp = df_20g_pro["Date"].unique().tolist()
len(df_3yp)

36

In [13]:
from tqdm import tqdm
mthly_mrp=[]
mthly_mrp.append(mth_1)
stock_on_hand=mth_1['Closing Stock']
for mth in tqdm(df_3yp[1:]):
    mtly_plan=mrp(df_mat=df_20g_pro,df_pro=df_20g_mat,pro_date=mth,soh=stock_on_hand)
    mthly_mrp.append(mtly_plan)
    stock_on_hand = mtly_plan['Closing Stock']

100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:00<00:00, 98.91it/s]

In [14]:
mthly_mrp[3]

,Date,Material Name,Stock on Hand,UOM,Safety Stock DOC,Usage,DOC,Reorder Qty,Closing Stock
0,2024-04-01,Animal Fat,3428906.46,KG,29.87,1530000.00,75.03,921015.00,2819921.46
1,2024-04-01,Plant Oil,3124114.78,KG,29.87,1394000.00,75.03,839147.00,2569261.78
2,2024-04-01,Caustic Soda,18275069.08,KG,19.00,1462000.00,67.44,880081.00,17693150.08
3,2024-04-01,Alkali,2514531.41,KG,29.87,1122000.00,75.03,675411.00,2067942.41
4,2024-04-01,Sodium Hydroxide,1523958.43,KG,29.87,680000.00,75.03,409340.00,1253298.43
5,2024-04-01,Potassium hydroxide,28341876.22,KG,27.82,1394000.00,109.69,839147.00,27787023.22
6,2024-04-01,colorant,2743125.17,KG,29.87,1224000.00,75.03,736812.00,2255937.17
7,2024-04-01,Texture,1523958.43,KG,29.87,680000.00,75.03,409340.00,1253298.43
8,2024-04-01,Scent,3809896.07,KG,29.87,1700000.00,75.03,1023350.00,3133246.07
9,2024-04-01,Silica,2819323.09,KG,29.87,1258000.00,75.03,757279.00,2318602.09
10,2024-04-01,marble pumice,1488069.50,KG,22.58,986000.00,50.53,593543.00,1095612.50
11,2024-04-01,Talc,2590729.33,KG,29.87,1156000.00,75.03,695878.00,2130607.33
25,2024-04-01,Shrink Wrap,3657500.23,KG,29.87,1632000.00,75.03,982416.00,3007916.23
26,2024-04-01,Luxe Bar Box,1523958.43,Pcs,29.87,680000.00,75.03,409340.00,1253298.43
27,2024-04-01,Luxe Bar Label,3047916.86,Pcs,29.87,1360000.00,75.03,818680.00,2506596.86
30,2024-04-01,Luxe Bar Carton,76197.92,Pcs,29.87,34000.00,75.03,20467.00,62664.92

In [15]:
# concatenate all the mthly requirement
mthly_mrp_3yp=pd.concat(mthly_mrp)
mthly_mrp_3yp

,Date,Material Name,Stock on Hand,UOM,Safety Stock DOC,Usage,DOC,Reorder Qty,Closing Stock
0,2024-01-01,Animal Fat,2000000.00,KG,29.87,900000.00,43.76,2349921.46,3449921.46
1,2024-01-01,Plant Oil,900000.00,KG,29.87,820000.00,21.62,3063261.78,3143261.78
2,2024-01-01,Caustic Soda,6500000.00,KG,19.00,860000.00,23.99,12655150.08,18295150.08
3,2024-01-01,Alkali,1200000.00,KG,29.87,660000.00,35.81,1989942.41,2529942.41
4,2024-01-01,Sodium Hydroxide,1897814.92,KG,29.87,400000.00,93.44,35483.51,1533298.43
...,...,...,...,...,...,...,...,...,...
11,2026-12-01 00:00:00,Talc,2452411.55,KG,29.87,1221693.44,71.03,834195.78,2064913.89
25,2026-12-01 00:00:00,Shrink Wrap,3462228.07,KG,29.87,1724743.68,71.03,1177688.16,2915172.55
26,2026-12-01 00:00:00,Luxe Bar Box,1442595.03,Pcs,29.87,718643.20,71.03,490703.40,1214655.23
27,2026-12-01 00:00:00,Luxe Bar Label,2885190.06,Pcs,29.87,1437286.40,71.03,981406.80,2429310.46
30,2026-12-01 00:00:00,Luxe Bar Carton,72129.75,Pcs,29.87,35932.16,71.03,24535.17,60732.76

In [18]:
# Export the file
filename = 'mthly_mrp_3yp.xlsx'
mthly_mrp_3yp.to_excel(filename, index=False)

PermissionError: [Errno 13] Permission denied: 'mthly_mrp_3yp.xlsx'